apiVersion: v2
name: prometheus-pagerduty-exporter
description: PagerDuty exporter for prometheus
type: application
version: 0.1.0
appVersion: "20.11.1"
home: https://github.com/webdevops/pagerduty-exporter/
sources:
  - https://github.com/webdevops/pagerduty-exporter/
keywords:
- pagerduty
- prometheus
- exporter
maintainers:
- email: nick-metz@web.de
  name: wasfree
